// Generates src/generated/prompts.ts from the Markdown source of truth in prompts/.
//
// The prompts live as plain Markdown so they are portable and editable by anyone,
// regardless of language or tooling. This script embeds them into a typed module
// so the library bundles cleanly with no runtime filesystem access.

import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const promptsDir = join(root, "prompts");
const outDir = join(root, "src", "generated");
const outFile = join(outDir, "prompts.ts");

const read = (...parts) => readFileSync(join(promptsDir, ...parts), "utf8").trim();

// Escape for safe embedding inside a TS template literal.
const lit = (s) => "`" + s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${") + "`";

const core = {
  PERSONA: read("persona.md"),
  GUARDRAILS: read("guardrails.md"),
  INDEPENDENCE: read("independence.md"),
  METHOD: read("method.md"),
  CALIBRATION: read("calibration.md"),
  SUMMARIZER: read("summary.md"),
};

const domains = {
  debugging: read("domains", "debugging.md"),
  reasoning: read("domains", "reasoning.md"),
  architecture: read("domains", "architecture.md"),
  review: read("domains", "review.md"),
  "ai-literacy": read("domains", "ai-literacy.md"),
};

const banner =
  "// AUTO-GENERATED by scripts/build-prompts.mjs - do not edit by hand.\n" +
  "// Edit the Markdown in prompts/ and re-run `npm run prebuild`.\n\n";

const body = [
  banner,
  ...Object.entries(core).map(([k, v]) => `export const ${k} = ${lit(v)};\n`),
  "\nexport const DOMAINS = {",
  ...Object.entries(domains).map(([k, v]) => `  ${JSON.stringify(k)}: ${lit(v)},`),
  "} as const;\n",
].join("\n");

if (!existsSync(outDir)) mkdirSync(outDir, { recursive: true });
writeFileSync(outFile, body, "utf8");

console.log(`✓ Wrote ${outFile}`);
